version: "3.8"

services:
  backend:
    build:
      context: backend
      dockerfile: ./Dockerfile
    ports:
      - "8800:8800"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DATABASE_URL=mysql://root@db:3306/test
    networks:
      - app-network
    volumes:
      - ./backend:/app
      - /app/node_modules
    restart: always

  db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=test
      - MYSQL_ROOT_HOST=%
    command: --default-authentication-plugin=mysql_native_password
    networks:
      - app-network
    restart: always
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init-scripts:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 5s
      retries: 10
      interval: 5s
  frontend:
    build:
      context: frontend
      dockerfile: ./Dockerfile
    ports:
      - "5173:5173"
    depends_on:
      - backend
    environment:
      - VITE_BACKEND_URL=http://localhost:8800
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
volumes:
  mysql_data:
